name: Integration tests

on:
  push:
    branches:
      - master
      - main
    paths:
      - "non-existent-path-to-never-trigger-this-workflow/**"
  pull_request:
    branches:
      - master
      - main
    paths:
      - "non-existent-path-to-never-trigger-this-workflow/**"

jobs:
  bypass:
    runs-on: ubuntu-latest
    steps:
      - name: Bypass
        run: echo "No redundant tests executed. Environment is clean."